version: 1

update_configs:

  - package_manager: "terraform"
    directory: "/"
    update_schedule: "daily"

  - package_manager: "terraform"
    directory: "/tests/baseline"
    update_schedule: "daily"

  - package_manager: "terraform"
    directory: "/tests/no_cloudtrail"
    update_schedule: "daily"

  - package_manager: "go:modules"
    directory: "/tests"
    update_schedule: "daily"

  - package_manager: "python"
    directory: "/"
    update_schedule: "live"

  - package_manager: "docker"
    directory: "/"
    update_schedule: "daily"

